-- This schema is generated based on the current DBContext. Please check the class Seeder to see.
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'meetyourplants') THEN
        CREATE SCHEMA meetyourplants;
    END IF;
END $EF$;


CREATE TABLE meetyourplants."EmailList" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    CONSTRAINT "PK_EmailList" PRIMARY KEY ("Id")
);


CREATE TABLE meetyourplants."Plant" (
    "PlantId" uuid NOT NULL,
    "Planted" timestamp with time zone,
    "PlantName" text NOT NULL,
    "PlantType" text NOT NULL,
    "PlantNotes" text,
    "LastWatered" timestamp with time zone,
    "WaterEvery" integer,
    "IsDead" boolean NOT NULL,
    CONSTRAINT "PK_Plant" PRIMARY KEY ("PlantId")
);


CREATE TABLE meetyourplants."User" (
    "UserId" uuid NOT NULL,
    "Hash" text NOT NULL,
    "Salt" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Birthday" timestamp with time zone,
    "Country" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("UserId")
);


CREATE TABLE meetyourplants."ConditionAlertPlant" (
    "ConditionAlertPlantId" uuid NOT NULL,
    "PlantId" uuid NOT NULL,
    "WaterNotify" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ConditionAlertPlant" PRIMARY KEY ("ConditionAlertPlantId"),
    CONSTRAINT "FK_ConditionAlertPlant_Plant_PlantId" FOREIGN KEY ("PlantId") REFERENCES meetyourplants."Plant" ("PlantId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."UserDevice" (
    "DeviceId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DeviceName" text NOT NULL,
    "DeviceDescription" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "WaitTime" text NOT NULL,
    CONSTRAINT "PK_UserDevice" PRIMARY KEY ("DeviceId"),
    CONSTRAINT "FK_UserDevice_User_UserId" FOREIGN KEY ("UserId") REFERENCES meetyourplants."User" ("UserId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."UserPlant" (
    "UserId" uuid NOT NULL,
    "PlantId" uuid NOT NULL,
    CONSTRAINT "PK_UserPlant" PRIMARY KEY ("UserId", "PlantId"),
    CONSTRAINT "FK_UserPlant_Plant_PlantId" FOREIGN KEY ("PlantId") REFERENCES meetyourplants."Plant" ("PlantId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPlant_User_UserId" FOREIGN KEY ("UserId") REFERENCES meetyourplants."User" ("UserId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."UserSettings" (
    "UserId" uuid NOT NULL,
    "Celsius" boolean NOT NULL,
    "DarkTheme" boolean NOT NULL,
    "ConfirmDialog" boolean NOT NULL,
    "SecretMode" boolean NOT NULL,
    CONSTRAINT "PK_UserSettings" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserSettings_User_UserId" FOREIGN KEY ("UserId") REFERENCES meetyourplants."User" ("UserId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."Weather" (
    "UserId" uuid NOT NULL,
    "City" text NOT NULL,
    "Country" text NOT NULL,
    CONSTRAINT "PK_Weather" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Weather_User_UserId" FOREIGN KEY ("UserId") REFERENCES meetyourplants."User" ("UserId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."ConditionAlertUserDevice" (
    "ConditionAlertUserDeviceId" uuid NOT NULL,
    "UserDeviceId" uuid NOT NULL,
    "SensorType" text NOT NULL,
    "Condition" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ConditionAlertUserDevice" PRIMARY KEY ("ConditionAlertUserDeviceId"),
    CONSTRAINT "FK_ConditionAlertUserDevice_UserDevice_UserDeviceId" FOREIGN KEY ("UserDeviceId") REFERENCES meetyourplants."UserDevice" ("DeviceId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."SensorHistory" (
    "SensorHistoryId" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "Temperature" double precision NOT NULL,
    "Humidity" double precision NOT NULL,
    "AirPressure" double precision NOT NULL,
    "AirQuality" integer NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SensorHistory" PRIMARY KEY ("SensorHistoryId"),
    CONSTRAINT "FK_SensorHistory_UserDevice_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES meetyourplants."UserDevice" ("DeviceId") ON DELETE CASCADE
);


CREATE TABLE meetyourplants."Alert" (
    "AlertId" uuid NOT NULL,
    "AlertUserId" uuid NOT NULL,
    "AlertName" text NOT NULL,
    "AlertDesc" text NOT NULL,
    "AlertTime" timestamp with time zone NOT NULL,
    "AlertPlantConditionId" uuid,
    "AlertDeviceConditionId" uuid,
    CONSTRAINT "PK_Alert" PRIMARY KEY ("AlertId"),
    CONSTRAINT "FK_Alert_ConditionAlertPlant_AlertPlantConditionId" FOREIGN KEY ("AlertPlantConditionId") REFERENCES meetyourplants."ConditionAlertPlant" ("ConditionAlertPlantId") ON DELETE SET NULL,
    CONSTRAINT "FK_Alert_ConditionAlertUserDevice_AlertDeviceConditionId" FOREIGN KEY ("AlertDeviceConditionId") REFERENCES meetyourplants."ConditionAlertUserDevice" ("ConditionAlertUserDeviceId") ON DELETE SET NULL,
    CONSTRAINT "FK_Alert_User_AlertUserId" FOREIGN KEY ("AlertUserId") REFERENCES meetyourplants."User" ("UserId") ON DELETE CASCADE
);


CREATE INDEX "IX_Alert_AlertDeviceConditionId" ON meetyourplants."Alert" ("AlertDeviceConditionId");


CREATE INDEX "IX_Alert_AlertPlantConditionId" ON meetyourplants."Alert" ("AlertPlantConditionId");


CREATE INDEX "IX_Alert_AlertUserId" ON meetyourplants."Alert" ("AlertUserId");


CREATE INDEX "IX_ConditionAlertPlant_PlantId" ON meetyourplants."ConditionAlertPlant" ("PlantId");


CREATE INDEX "IX_ConditionAlertUserDevice_UserDeviceId" ON meetyourplants."ConditionAlertUserDevice" ("UserDeviceId");


CREATE INDEX "IX_SensorHistory_DeviceId" ON meetyourplants."SensorHistory" ("DeviceId");


CREATE INDEX "IX_UserDevice_UserId" ON meetyourplants."UserDevice" ("UserId");


CREATE INDEX "IX_UserPlant_PlantId" ON meetyourplants."UserPlant" ("PlantId");


