name: DevOps Flyway Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flyway configuration
        run: |
          mkdir -p ./flyway/conf
          echo "flyway.url=jdbc:postgresql://${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/${{ secrets.DATABASE_NAME }}" >> ./flyway/conf/flyway.conf
          echo "flyway.user=${{ secrets.DATABASE_USER }}" >> ./flyway/conf/flyway.conf
          echo "flyway.password=${{ secrets.DATABASE_PASSWORD }}" >> ./flyway/conf/flyway.conf
          echo "flyway.locations=filesystem:/flyway/db/migrations" >> ./flyway/conf/flyway.conf

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/db:/flyway/db \
            -v ${{ github.workspace }}/flyway/conf:/flyway/conf \
            flyway/flyway:latest migrate