name: Firebase Deploy Frontend

on:
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      - run: cd client && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: 'client'
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASVWEATHERSTATION }}
          channelId: live
          projectId: easvweatherstation
