name: Mutation Testing
on:
  workflow_dispatch:

jobs:
  mutation_testing:
    name: Mutation Testing
    runs-on: ubuntu-latest
    env:
      DOTNET_ROLL_FORWARD: LatestMajor
      APPOPTIONS__DbConnectionString: ${{secrets.DBCONNECTIONSTRING}}
      APPOPTIONS__JwtSecret: ${{secrets.JWT_TOKEN}}
      APPOPTIONS__MQTT_BROKER_HOST: ${{secrets.MQTT_BROKER_HOST}}
      APPOPTIONS__MQTT_USERNAME: ${{secrets.MQTT_USERNAME}}
      APPOPTIONS__EMAIL_SENDER_USERNAME: ${{secrets.EMAIL_SENDER_USERNAME}}
      APPOPTIONS__EMAIL_SENDER_PASSWORD: ${{secrets.EMAIL_SENDER_PASSWORD}}
      APPOPTIONS__JWT_EMAIL_SECRET: ${{secrets.JWT_EMAIL_SECRET}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages & global tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet/tools/.store
            ~/.dotnet/tools
            ~/.dotnet/toolresolver
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Install Stryker .NET globally
        run: dotnet tool install --global dotnet-stryker

      - name: Generate stryker-config.json
        working-directory: server/Startup.Tests
        run: |
          cat > stryker-config.json <<'JSON'
          {
            "$schema": "https://stryker-mutator.io/stryker-schema.json",
            "solution": "../DrivhusApplikation.sln",
            "mutate": [
              "server/Api.Rest/**/*.cs",
              "server/Api.Websocket/**/*.cs",
              "server/Application/**/*.cs",
              "server/Infrastructure.MQTT/**/*.cs",
              "server/Infrastructure.Postgres/**/*.cs",
              "server/Infrastructure.Websocket/**/*.cs",
              "!server/Core.Domain/**/*.cs",
              "!server/Infrastructure.Postgres.Scaffolding/**",
              "!server/Startup/**"
            ],
            "coverage-analysis": "perTest",
            "thresholds": { "break": 80 },
            "concurrency": "auto",
            "max-test-run-time": 120
          }
          JSON

      - name: Run Mutation Tests (Stryker)
        working-directory: server/Startup.Tests
        run: dotnet stryker --reporter "html"
        continue-on-error: true

      - name: Upload Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: server/Startup.Tests/StrykerOutput/**/reports/mutation-report.html
  