name: Mutation Testing
on: [ workflow_dispatch ]

jobs:
  mutation_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - "server/Api.Rest/Api.Rest.csproj"
          - "server/Api.Websocket/Api.Websocket.csproj"
          - "server/Application/Application.csproj"
          - "server/Infrastructure.MQTT/Infrastructure.MQTT.csproj"
          - "server/Infrastructure.Postgres/Infrastructure.Postgres.csproj"
          - "server/Infrastructure.Websocket/Infrastructure.Websocket.csproj"
    env:
      APPOPTIONS__DbConnectionString: ${{secrets.DBCONNECTIONSTRING}}
      APPOPTIONS__JwtSecret: ${{secrets.JWT_TOKEN}}
      APPOPTIONS__MQTT_BROKER_HOST: ${{secrets.MQTT_BROKER_HOST}}
      APPOPTIONS__MQTT_USERNAME: ${{secrets.MQTT_USERNAME}}
      APPOPTIONS__EMAIL_SENDER_USERNAME: ${{secrets.EMAIL_SENDER_USERNAME}}
      APPOPTIONS__EMAIL_SENDER_PASSWORD: ${{secrets.EMAIL_SENDER_PASSWORD}}
      APPOPTIONS__JWT_EMAIL_SECRET: ${{secrets.JWT_EMAIL_SECRET}}
    
    name: Stryker on ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: 8.0.x }

      - name: Install Stryker .NET
        run: dotnet tool install --global dotnet-stryker
          
      - name: Run Stryker
        run: |
          dotnet stryker \
            --project "${{ matrix.project }}" \
            --test-project "server/Startup.Tests/Startup.Tests.csproj" \
            --threshold-break 80 \
            --reporters "html"
        env:
          DOTNET_ROLL_FORWARD: LatestMajor
        continue-on-error: true

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-${{ matrix.project }}
          path: StrykerOutput/**/reports/mutation-report.html
  