name: Mutation Testing
on:
  workflow_dispatch:

jobs:
  mutation_testing:
    name: Mutation Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet & dotnet‑tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet/tools
            ~/.dotnet/toolresolver
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-stryker

      - name: Generate stryker-config.json
        run: |
          cat > stryker-config.json <<'JSON'
          {
            "$schema": "https://stryker-mutator.io/stryker-schema.json",
            "solution": "../DrivhusApplikation.sln",
            "mutate": [ "!**/Startup/**" ],
            "coverage-analysis": "perTest",
            "thresholds": {
              "break": 80
            },
            "concurrency": "auto",
            "max-test-run-time": 120
          }
          JSON
        working-directory: server/Startup.Tests

      - name: Run Mutation Tests (Stryker)
        run: dotnet stryker --reporter "html"
        env:
          DOTNET_ROLL_FORWARD: LatestMajor
        continue-on-error: true

      - name: Upload Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: StrykerOutput/**/reports/mutation-report.html
  