name: Mutation Testing
on: [ workflow_dispatch ]

jobs:
  mutation_testing:
    runs-on: self-hosted
    
    env:
      APPOPTIONS__DbConnectionString: ${{ secrets.DBCONNECTIONSTRING }}
      APPOPTIONS__JwtSecret:        ${{ secrets.JWT_TOKEN }}
      APPOPTIONS__MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST }}
      APPOPTIONS__MQTT_USERNAME:    ${{ secrets.MQTT_USERNAME }}
      APPOPTIONS__EMAIL_SENDER_USERNAME: ${{ secrets.EMAIL_SENDER_USERNAME }}
      APPOPTIONS__EMAIL_SENDER_PASSWORD: ${{ secrets.EMAIL_SENDER_PASSWORD }}
      APPOPTIONS__JWT_EMAIL_SECRET: ${{ secrets.JWT_EMAIL_SECRET }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install Stryker .NET
        run: dotnet tool install --global dotnet-stryker

      - name: Run mutation tests
        run: dotnet stryker --reporter html
        continue-on-error: true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report
          path: StrykerOutput/**/reports/mutation-report.html