name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags teste213123

      - name: Get Current Version
        id: current_version
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          if [ -z "$TAG" ]; then
            VERSION="0.0.0"
          else
            VERSION="${TAG#v}"
          fi

          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Current version: $VERSION"

      - name: Bump Version Based on Commit
        id: version_bump
        run: |
          VERSION="${{ env.CURRENT_VERSION }}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -q "(MAJOR)"; then
            ((MAJOR+=1)); MINOR=0; PATCH=0
          elif echo "$COMMIT_MSG" | grep -q "(MINOR)"; then
            ((MINOR+=1)); PATCH=0
          elif echo "$COMMIT_MSG" | grep -q "(PATCH)"; then
            ((PATCH+=1))
          else
            echo "No version bump keyword found, keeping current version."
            echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
            exit 0
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"

      - name: Create Git Tag
        run: |
          NEW_TAG="v${{ env.NEW_VERSION }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.NEW_VERSION }}"
          name: "v${{ env.NEW_VERSION }}"
          generateReleaseNotes: true
          body: |
            🚀 This release includes the following container image:
            https://ghcr.io/${{ github.repository }}:${{ env.NEW_VERSION }}
          makeLatest: legacy
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
