name: Version
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Application Version
        id: semver-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"
          tag_prefix: "v"
          enable_prerelease_mode: false
          search_commit_body: true

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.semver-app.outputs.version }}
          name: v${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            🚀 This release includes the following container image:
            https://ghcr.io/${{ github.repository }}:v${{ steps.semver-app.outputs.version }}
          makeLatest: legacy
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
